# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c1cf540a737a8b3a1c4a027eb296cf7822dc3087c80e95d1a28ec9dbf317f0c3e317b94847dd1f0e0404c8de36c6b722ec3319cc168bf743db4b8b73fa25467

test:
  secret_key_base: c2ce388d0b75bccb505a1b0b63f405f4265cd8f8680591cd684749d7c432f3a62f9a88111df155273a3a245e2d75f99ac0be55b0e9ccdd04f7fa6cd013068ea6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
